apiVersion: v1
kind: Service
metadata:
  name: hw-4-2-svc
spec:
  selector:
    app: hw-4
  ports:
    - name: for-nginx
      nodePort: 30500
      targetPort: 80
      port: 80
    - name: for-multitool
      nodePort: 30501
      port: 8080
      targetPort: 8080
  type: NodePort
