apiVersion: v1
kind: Service
metadata:
  name: hw-4-svc
  namespace: default
spec:
  selector:
    app: hw-4
  ports:
    - protocol: TCP
      name: nginx
      port: 9001
      targetPort: 80
    - protocol: TCP
      name: multitool
      port: 9002
      targetPort: 8080
